package com.example.accessingdatarest;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.fasterxml.jackson.databind.exc.InvalidDefinitionException;

@RestController // Since we are using JpaRepository all methods return JSON by default...
@RequestMapping(path="/people")
public class PeopleController {
	
	@Autowired
	PersonRepository personRepo;
	
	/**
	 * Adds a Person entry to database.
	 * @param A person Object
	 * @return The persisted person object
	 * @author Camilo F.
	 */
	@PostMapping("/")
	public Person addPerson(@RequestBody Person p) {
		System.out.println(p);
		personRepo.save(p);
		return p;
	}
	
	/**
	 * Retrieves every person persisted in database
	 * @return a list containing all entries
	 * @author Camilo F.
	 */
	@RequestMapping("/")
	public List<Person> getPeople() {
		return personRepo.findAll();
	}
	
	/**
	 * Updates a person by removing it from Database and adding a new one
	 * with the same id. Returns the removed element
	 * @param id - the id of item to update
	 * @param newPerson - object that holds the new data
	 * @return - the replaced item, for undo purposes
	 * @author Camilo F.
	 */
	@PutMapping("/{id}")
	public Person updatePerson(@PathVariable long id, @RequestBody Person newPerson) throws InvalidDefinitionException {
		Person oldPerson;
		try {
			oldPerson = personRepo.getOne(id);
			oldPerson.setFirstName(newPerson.getFirstName());
			oldPerson.setLastName(newPerson.getLastName());
			return oldPerson;
		} catch(EmptyResultDataAccessException e) {
			return new Person();
		} catch(Exception e) {
			System.out.println("[ERROR] InvocationException");
			return new Person();
		}
	}
	
	@DeleteMapping("/{id}")
	public Person deletePerson(@PathVariable long id) {
		Person deletedPerson;
		try {
			deletedPerson = personRepo.getOne(id);
			personRepo.deleteById(id);
			return deletedPerson;
		} catch(EmptyResultDataAccessException e) {
			return new Person();
		}
	}
	
	
}

/**
@Controller // This means that this class is a Controller
@RequestMapping(path="/people") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private PersonRepository personRepository;
  
  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewUser (@RequestParam String firstName , @RequestParam String lastName) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Person n = new Person(firstName, lastName);
    personRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Person> getAllUsers() {
    // This returns a JSON or XML with the users
    return personRepository.findAll();
  }
}
*/